# Generated by Django 3.1 on 2020-09-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_message_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='viewed',
            field=models.BooleanField(default=True),
        ),
    ]
