# Generated by Django 3.1 on 2020-09-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20200904_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='viewed',
        ),
    ]
