# Generated by Django 3.1 on 2020-09-04 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='display_name',
        ),
    ]
