# Generated by Django 3.1 on 2020-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_remove_myuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(default='There is no biography information associated with this Twittercloner'),
        ),
    ]
