# Generated by Django 3.1 on 2020-09-05 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0004_auto_20200905_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
