# Generated by Django 3.1 on 2020-09-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0005_myuser_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='What I Do'),
        ),
    ]
