# Generated by Django 3.1 on 2020-09-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0006_auto_20200905_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(default='', max_length=80, verbose_name='What I Do'),
        ),
    ]
