# Generated by Django 3.1 on 2020-09-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0007_auto_20200905_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='What I Do'),
        ),
    ]
