# Generated by Django 3.1 on 2020-09-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0008_auto_20200905_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
